//! Controller for `docs.html`: chart switching, pan and zoom, the detail panel
//! for the box being read (what it does, where it leads, its code), hover
//! focus, the guided tour and deep links (`docs.html#chart/box`).
//!
//! The diagrams are static SVG generated by `ccm-docgen`, and everything the
//! panel shows comes from the JSON block it writes into the page, so this only
//! moves a view box around and copies prepared text into place. Without it the
//! page is still readable: the charts are plain SVG.

use crate::{restore_theme, set_text};
use serde_json::Value;
use std::cell::RefCell;
use std::collections::BTreeMap;
use std::rc::Rc;
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Document, Element, HtmlElement, KeyboardEvent, MouseEvent, WheelEvent};

/// Zoom range. Below the floor the labels stop being readable; above the
/// ceiling there is nothing left to see.
const MIN_SCALE: f64 = 0.2;
const MAX_SCALE: f64 = 3.0;

/// How the detail panel names each kind of box.
fn kind_label(kind: &str) -> &'static str {
    match kind {
        "entry" => "Start",
        "decision" => "Question",
        "end" => "Finish",
        "aside" => "Helper",
        _ => "Step",
    }
}

/// The part of a chart in view, as an SVG view box.
#[derive(Clone, Copy)]
struct View {
    x: f64,
    y: f64,
    w: f64,
    h: f64,
    /// The chart's own size.
    width: f64,
    height: f64,
    /// Stage size the view was last fitted to, to keep the zoom on resize.
    stage_w: f64,
}

struct Docs {
    document: Document,
    data: Value,
    chart: String,
    selected: Option<String>,
    views: BTreeMap<String, View>,
    drag: Option<(f64, f64)>,
}

impl Docs {
    fn chart_data(&self) -> &Value {
        &self.data["charts"][&self.chart]
    }

    fn query(&self, selector: &str) -> Option<Element> {
        self.document.query_selector(selector).ok().flatten()
    }

    fn by_id(&self, id: &str) -> Option<Element> {
        self.document.get_element_by_id(id)
    }

    fn section(&self) -> Option<Element> {
        self.by_id(&format!("panel-{}", self.chart))
    }

    fn stage(&self) -> Option<Element> {
        self.section()?.query_selector(".stage").ok().flatten()
    }

    fn stage_size(&self) -> (f64, f64) {
        self.stage().map_or((0.0, 0.0), |stage| {
            let rect = stage.get_bounding_client_rect();
            (rect.width(), rect.height())
        })
    }

    /// Writes the current chart's view box and zoom level into the page.
    fn apply(&mut self) {
        let (sw, sh) = self.stage_size();
        let Some(view) = self.views.get_mut(&self.chart) else {
            return;
        };
        // Keep part of the chart in view: never past its edges by more than a margin.
        let margin = 40.0;
        let clamp = |pos: f64, size: f64, total: f64| {
            if size >= total + 2.0 * margin {
                (total - size) / 2.0
            } else {
                pos.clamp(-margin, total + margin - size)
            }
        };
        view.x = clamp(view.x, view.w, view.width);
        view.y = clamp(view.y, view.h, view.height);
        let view = *view;
        let Some(section) = self.section() else {
            return;
        };
        if let Ok(Some(svg)) = section.query_selector("svg.chart") {
            let _ = svg.set_attribute(
                "viewBox",
                &format!("{:.1} {:.1} {:.1} {:.1}", view.x, view.y, view.w, view.h),
            );
        }
        if let Ok(Some(level)) = section.query_selector(".zoom-level") {
            let scale = if view.w > 0.0 && view.h > 0.0 {
                (sw / view.w).min(sh / view.h)
            } else {
                1.0
            };
            level.set_text_content(Some(&format!("{:.0}%", scale * 100.0)));
        }
    }

    /// Shows the whole chart, at most at 100 %.
    fn fit(&mut self) {
        let (sw, sh) = self.stage_size();
        let Some(view) = self.views.get_mut(&self.chart) else {
            return;
        };
        if sw <= 0.0 {
            return;
        }
        let scale = 1.0_f64
            .min((sw - 24.0) / view.width)
            .min((sh - 64.0) / view.height)
            .max(MIN_SCALE);
        let (w, h) = (sw / scale, sh / scale);
        view.x = (view.width - w) / 2.0;
        view.y = (view.height - h) / 2.0 + 20.0 / scale;
        view.w = w;
        view.h = h;
        view.stage_w = sw;
        self.apply();
    }

    /// A readable start: the chart's full width (at most 100 %), from the top.
    fn fit_width(&mut self) {
        let (sw, sh) = self.stage_size();
        let Some(view) = self.views.get_mut(&self.chart) else {
            return;
        };
        if sw <= 0.0 {
            return;
        }
        let scale = 1.0_f64.min((sw - 24.0) / view.width).max(MIN_SCALE);
        if view.height * scale <= sh - 56.0 {
            self.fit();
            return;
        }
        let (w, h) = (sw / scale, sh / scale);
        view.x = (view.width - w) / 2.0;
        view.y = 0.0;
        view.w = w;
        view.h = h;
        view.stage_w = sw;
        self.apply();
    }

    fn scale(&self) -> f64 {
        let (sw, _) = self.stage_size();
        self.views
            .get(&self.chart)
            .map_or(1.0, |view| if view.w > 0.0 { sw / view.w } else { 1.0 })
    }

    /// Zooms about a point of the stage (its centre when `at` is `None`).
    fn zoom(&mut self, factor: f64, at: Option<(f64, f64)>) {
        let (sw, sh) = self.stage_size();
        let scale = self.scale();
        let Some(view) = self.views.get_mut(&self.chart) else {
            return;
        };
        let next = (scale * factor).clamp(MIN_SCALE, MAX_SCALE);
        let (px, py) = at.unwrap_or((sw / 2.0, sh / 2.0));
        let (wx, wy) = (view.x + px / scale, view.y + py / scale);
        view.w = sw / next;
        view.h = sh / next;
        view.x = wx - px / next;
        view.y = wy - py / next;
        self.apply();
    }

    fn pan(&mut self, dx: f64, dy: f64) {
        let scale = self.scale();
        if let Some(view) = self.views.get_mut(&self.chart) {
            view.x -= dx / scale;
            view.y -= dy / scale;
        }
        self.apply();
    }

    /// The stage changed size: keep the zoom level and the view's centre.
    fn resized(&mut self) {
        let (sw, sh) = self.stage_size();
        let Some(view) = self.views.get_mut(&self.chart) else {
            return;
        };
        if sw <= 0.0 || view.stage_w <= 0.0 || view.w <= 0.0 {
            return;
        }
        let scale = view.stage_w / view.w;
        let (cx, cy) = (view.x + view.w / 2.0, view.y + view.h / 2.0);
        view.w = sw / scale;
        view.h = sh / scale;
        view.x = cx - view.w / 2.0;
        view.y = cy - view.h / 2.0;
        view.stage_w = sw;
        self.apply();
    }

    /// Keeps a box in view, centring it when it is not comfortably visible.
    fn reveal(&mut self, id: &str) {
        let b = &self.chart_data()["nodes"][id]["box"];
        let (bx, by, bw, bh) = (
            b[0].as_f64().unwrap_or(0.0),
            b[1].as_f64().unwrap_or(0.0),
            b[2].as_f64().unwrap_or(0.0),
            b[3].as_f64().unwrap_or(0.0),
        );
        let scale = self.scale();
        let Some(view) = self.views.get_mut(&self.chart) else {
            return;
        };
        let m = 40.0 / scale;
        let visible = bx > view.x + m
            && by > view.y + m
            && bx + bw < view.x + view.w - m
            && by + bh < view.y + view.h - m - 50.0 / scale;
        if !visible {
            view.x = bx + bw / 2.0 - view.w / 2.0;
            view.y = by + bh / 2.0 - view.h / 2.0 + 20.0 / scale;
            self.apply();
        }
    }

    /// Brings a box and its connections forward; `None` clears the focus.
    fn set_focus(&self, id: Option<&str>) {
        let Some(stage) = self.stage() else {
            return;
        };
        let _ = stage
            .class_list()
            .toggle_with_force("focusing", id.is_some());
        each(&stage, ".hot", |el| {
            let _ = el.class_list().remove_1("hot");
        });
        each(&stage, ".edge", |el| {
            let tone = el.get_attribute("data-tone").unwrap_or_default();
            let _ = el.set_attribute("marker-end", &format!("url(#ah-{}-{tone})", self.chart));
        });
        let Some(id) = id else {
            return;
        };
        let node = &self.chart_data()["nodes"][id];
        let mut near = vec![id.to_owned()];
        for key in ["in", "out"] {
            near.extend(strings(&node[key]));
        }
        each(&stage, ".node", |el| {
            if el
                .get_attribute("data-id")
                .is_some_and(|n| near.contains(&n))
            {
                let _ = el.class_list().add_1("hot");
            }
        });
        each(&stage, ".edge, .chip", |el| {
            let touches = el.get_attribute("data-from").as_deref() == Some(id)
                || el.get_attribute("data-to").as_deref() == Some(id);
            if touches {
                let _ = el.class_list().add_1("hot");
                if el.class_list().contains("edge") {
                    let _ = el.set_attribute("marker-end", &format!("url(#ah-{}-hot)", self.chart));
                }
            }
        });
    }

    fn show_detail(&mut self, id: &str) {
        let node = self.chart_data()["nodes"][id].clone();
        if node.is_null() {
            return;
        }
        self.selected = Some(id.to_owned());
        if let Some(stage) = self.stage() {
            each(&stage, ".node.selected", |el| {
                let _ = el.class_list().remove_1("selected");
            });
            if let Ok(Some(el)) = stage.query_selector(&format!(".node[data-id=\"{id}\"]")) {
                let _ = el.class_list().add_1("selected");
            }
        }
        self.set_focus(Some(id));
        self.reveal(id);

        if let Some(body) = self.document.body() {
            let _ = body.class_list().add_1("has-detail");
        }
        self.toggle("#detail .detail-empty", true);
        self.toggle("#detail .detail-body", false);

        let kind = node["kind"].as_str().unwrap_or("step");
        if let Some(chip) = self.by_id("d_kind") {
            chip.set_text_content(Some(kind_label(kind)));
            chip.set_class_name(&format!("kind-chip k-{kind}"));
        }
        let order = strings(&self.chart_data()["order"]);
        let pos = order.iter().position(|step| step == id).unwrap_or(0);
        set_text(
            &self.document,
            "d_pos",
            &format!("{} / {}", pos + 1, order.len()),
        );
        self.disable("d_prev", pos == 0);
        self.disable("d_next", pos + 1 >= order.len());
        set_text(
            &self.document,
            "d_title",
            node["title"].as_str().unwrap_or(""),
        );
        set_text(&self.document, "d_sub", node["sub"].as_str().unwrap_or(""));
        if let Some(desc) = self.by_id("d_desc") {
            desc.set_inner_html(node["desc"].as_str().unwrap_or(""));
        }

        // "from" and "next" buttons for walking the chart by its arrows.
        let nodes = &self.chart_data()["nodes"];
        let button = |to: &str, label: Option<&str>| {
            let title = escape(nodes[to]["title"].as_str().unwrap_or(to));
            let label = label
                .map(|l| format!("<b>{}</b>&nbsp;", escape(l)))
                .unwrap_or_default();
            format!(r#"<button type="button" data-go="{to}">{label}{title}</button>"#)
        };
        let ins: String = strings(&node["in"])
            .iter()
            .map(|from| button(from, None))
            .collect();
        let outs: String = strings(&node["out"])
            .iter()
            .map(|to| button(to, node["labels"][to.as_str()].as_str()))
            .collect();
        let mut links = String::new();
        if !ins.is_empty() {
            links.push_str(&format!(r#"<span class="dir">from</span>{ins}"#));
        }
        if !outs.is_empty() {
            links.push_str(&format!(r#"<span class="dir">next</span>{outs}"#));
        }
        if let Some(el) = self.by_id("d_links") {
            el.set_inner_html(&links);
        }

        let code = node["code"]
            .as_str()
            .map(|name| self.chart_data()["code"][name].clone());
        self.toggle("#d_code", code.is_none());
        if let Some(code) = code {
            let line = code["line"].as_u64().unwrap_or(1);
            set_text(
                &self.document,
                "d_file",
                &format!("{}:{line}", code["path"].as_str().unwrap_or("")),
            );
            if let Some(link) = self.by_id("d_github") {
                let _ = link.set_attribute("href", code["url"].as_str().unwrap_or("#"));
            }
            if let Some(src) = self.by_id("d_src") {
                let _ = src.set_attribute("style", &format!("--start: {}", line.saturating_sub(1)));
                let lines: Vec<String> = strings(&code["html"])
                    .iter()
                    .map(|l| format!(r#"<span class="line">{l}</span>"#))
                    .collect();
                src.set_inner_html(&lines.join("\n"));
            }
            set_text(&self.document, "d_copy", "Copy");
        }
        replace_hash(&format!("#{}/{id}", self.chart));
    }

    fn clear_detail(&mut self) {
        self.selected = None;
        if let Some(stage) = self.stage() {
            each(&stage, ".node.selected", |el| {
                let _ = el.class_list().remove_1("selected");
            });
        }
        self.set_focus(None);
        self.toggle("#detail .detail-empty", false);
        self.toggle("#detail .detail-body", true);
        if let Some(body) = self.document.body() {
            let _ = body.class_list().remove_1("has-detail");
        }
        replace_hash(&format!("#{}", self.chart));
    }

    fn step_tour(&mut self, delta: isize) {
        let order = strings(&self.chart_data()["order"]);
        if order.is_empty() {
            return;
        }
        let pos = self
            .selected
            .as_ref()
            .and_then(|id| order.iter().position(|step| step == id))
            .map_or(-1, |p| isize::try_from(p).unwrap_or(0));
        let last = isize::try_from(order.len() - 1).unwrap_or(0);
        let next = usize::try_from((pos + delta).clamp(0, last)).unwrap_or(0);
        let id = order[next].clone();
        self.show_detail(&id);
    }

    fn show_chart(&mut self, id: &str, step: Option<&str>) {
        let id = if self.data["charts"][id].is_null() {
            first_chart(&self.document).unwrap_or_default()
        } else {
            id.to_owned()
        };
        let changed = id != self.chart;
        self.chart = id;
        each(
            &self.document.document_element().expect("root"),
            ".chart-panel",
            |el| {
                let hidden = el.get_attribute("data-chart").as_deref() != Some(self.chart.as_str());
                if hidden {
                    let _ = el.set_attribute("hidden", "");
                } else {
                    let _ = el.remove_attribute("hidden");
                }
            },
        );
        each(
            &self.document.document_element().expect("root"),
            ".nav-item",
            |el| {
                if el.get_attribute("data-chart").as_deref() == Some(self.chart.as_str()) {
                    let _ = el.set_attribute("aria-current", "page");
                } else {
                    let _ = el.remove_attribute("aria-current");
                }
            },
        );
        if !self.views.contains_key(&self.chart) {
            let svg = self
                .section()
                .and_then(|s| s.query_selector("svg.chart").ok().flatten());
            let size = |name: &str| {
                svg.as_ref()
                    .and_then(|el| el.get_attribute(name))
                    .and_then(|v| v.parse::<f64>().ok())
                    .unwrap_or(1000.0)
            };
            let (width, height) = (size("data-width"), size("data-height"));
            self.views.insert(
                self.chart.clone(),
                View {
                    x: 0.0,
                    y: 0.0,
                    w: width,
                    h: height,
                    width,
                    height,
                    stage_w: 0.0,
                },
            );
            self.fit_width();
        } else if changed {
            self.fit_width();
        }
        if changed {
            if let Some(content) = self.by_id("charts") {
                content.set_scroll_top(0);
            }
        }
        match step {
            Some(step) if !self.chart_data()["nodes"][step].is_null() => self.show_detail(step),
            _ if changed => self.clear_detail(),
            _ => {}
        }
    }

    fn toggle(&self, selector: &str, hidden: bool) {
        if let Some(el) = self.query(selector) {
            if hidden {
                let _ = el.set_attribute("hidden", "");
            } else {
                let _ = el.remove_attribute("hidden");
            }
        }
    }

    fn disable(&self, id: &str, disabled: bool) {
        if let Some(el) = self.by_id(id) {
            if disabled {
                let _ = el.set_attribute("disabled", "");
            } else {
                let _ = el.remove_attribute("disabled");
            }
        }
    }
}

fn escape(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn strings(value: &Value) -> Vec<String> {
    value
        .as_array()
        .map(|items| {
            items
                .iter()
                .filter_map(|v| v.as_str().map(str::to_owned))
                .collect()
        })
        .unwrap_or_default()
}

/// Runs `f` on every element under `root` matching `selector`.
fn each(root: &Element, selector: &str, mut f: impl FnMut(&Element)) {
    if let Ok(list) = root.query_selector_all(selector) {
        for index in 0..list.length() {
            if let Some(el) = list.item(index).and_then(|n| n.dyn_into::<Element>().ok()) {
                f(&el);
            }
        }
    }
}

fn replace_hash(hash: &str) {
    if let Some(history) = web_sys::window().and_then(|w| w.history().ok()) {
        let _ = history.replace_state_with_url(&JsValue::NULL, "", Some(hash));
    }
}

fn first_chart(document: &Document) -> Option<String> {
    document
        .query_selector(".nav-item")
        .ok()
        .flatten()
        .and_then(|el| el.get_attribute("data-chart"))
}

/// The chart and box named by the address: `#chart` or `#chart/box`.
fn from_hash(state: &Rc<RefCell<Docs>>) {
    let hash = web_sys::window()
        .and_then(|w| w.location().hash().ok())
        .unwrap_or_default();
    let hash = hash.trim_start_matches('#');
    let (chart, step) = match hash.split_once('/') {
        Some((chart, step)) => (chart.to_owned(), Some(step.to_owned())),
        None => (hash.to_owned(), None),
    };
    state.borrow_mut().show_chart(&chart, step.as_deref());
}

/// Copies the code being read to the clipboard.
fn copy_code(document: &Document) {
    let text = document
        .get_element_by_id("d_src")
        .and_then(|el| el.text_content())
        .unwrap_or_default();
    let written = web_sys::window()
        .and_then(|w| js_sys::Reflect::get(&w, &"navigator".into()).ok())
        .and_then(|n| js_sys::Reflect::get(&n, &"clipboard".into()).ok())
        .and_then(|clipboard| {
            let write = js_sys::Reflect::get(&clipboard, &"writeText".into()).ok()?;
            write
                .dyn_into::<js_sys::Function>()
                .ok()?
                .call1(&clipboard, &text.into())
                .ok()
        })
        .is_some();
    set_text(
        document,
        "d_copy",
        if written { "Copied" } else { "Copy failed" },
    );
}

fn listen<E: wasm_bindgen::convert::FromWasmAbi + 'static>(
    target: &web_sys::EventTarget,
    event: &str,
    handler: impl FnMut(E) + 'static,
) {
    let closure = Closure::<dyn FnMut(E)>::new(handler);
    let _ = target.add_event_listener_with_callback(event, closure.as_ref().unchecked_ref());
    closure.forget();
}

/// The box an event happened on, if any.
fn node_at(target: Option<web_sys::EventTarget>) -> Option<String> {
    target?
        .dyn_into::<Element>()
        .ok()?
        .closest(".node")
        .ok()
        .flatten()?
        .get_attribute("data-id")
}

/// Entry point for `docs.html`.
///
/// # Errors
///
/// Returns an error when the window or document is unavailable, or the page
/// data is missing or malformed.
#[wasm_bindgen]
#[allow(clippy::too_many_lines)]
pub fn start_docs() -> Result<(), JsValue> {
    let window = web_sys::window().ok_or_else(|| JsValue::from_str("window unavailable"))?;
    let document = window
        .document()
        .ok_or_else(|| JsValue::from_str("document unavailable"))?;
    restore_theme(&document);
    crate::hook_theme_toggle(&document, || {});

    let raw = document
        .get_element_by_id("doc-data")
        .and_then(|el| el.text_content())
        .ok_or_else(|| JsValue::from_str("page data missing"))?;
    let data: Value =
        serde_json::from_str(&raw).map_err(|e| JsValue::from_str(&format!("page data: {e}")))?;

    let state = Rc::new(RefCell::new(Docs {
        document: document.clone(),
        data,
        chart: String::new(),
        selected: None,
        views: BTreeMap::new(),
        drag: None,
    }));

    let root: Element = document.document_element().expect("root");

    // The chart list.
    each(&root, ".nav-item", |el| {
        let id = el.get_attribute("data-chart").unwrap_or_default();
        let state = Rc::clone(&state);
        listen(el, "click", move |event: MouseEvent| {
            event.prevent_default();
            state.borrow_mut().show_chart(&id, None);
            replace_hash(&format!("#{id}"));
        });
    });

    // Each chart's own tools.
    each(&root, ".chart-panel", |section| {
        let chart = section.get_attribute("data-chart").unwrap_or_default();
        each(section, "[data-zoom]", |button| {
            let action = button.get_attribute("data-zoom").unwrap_or_default();
            let state = Rc::clone(&state);
            listen(button, "click", move |_: MouseEvent| {
                let mut docs = state.borrow_mut();
                match action.as_str() {
                    "in" => docs.zoom(1.25, None),
                    "out" => docs.zoom(0.8, None),
                    _ => docs.fit(),
                }
            });
        });
        if let Ok(Some(button)) = section.query_selector(".tour-start") {
            let state = Rc::clone(&state);
            let chart = chart.clone();
            listen(&button, "click", move |_: MouseEvent| {
                let mut docs = state.borrow_mut();
                let first = strings(&docs.data["charts"][&chart]["order"])
                    .into_iter()
                    .next();
                if let Some(first) = first {
                    docs.show_detail(&first);
                }
            });
        }
    });

    let charts: HtmlElement = crate::element(&document, "charts");

    // Click a box to read it; hover to see its connections.
    {
        let state = Rc::clone(&state);
        listen(&charts, "click", move |event: MouseEvent| {
            if let Some(id) = node_at(event.target()) {
                state.borrow_mut().show_detail(&id);
            }
        });
    }
    {
        let state = Rc::clone(&state);
        listen(&charts, "mouseover", move |event: MouseEvent| {
            let docs = state.borrow();
            match node_at(event.target()) {
                Some(id) => docs.set_focus(Some(&id)),
                None => docs.set_focus(docs.selected.as_deref()),
            }
        });
    }

    // Drag to pan; the wheel scrolls, Ctrl + wheel (or a pinch) zooms.
    {
        let state = Rc::clone(&state);
        listen(&charts, "mousedown", move |event: MouseEvent| {
            let on_stage = event
                .target()
                .and_then(|t| t.dyn_into::<Element>().ok())
                .is_some_and(|el| el.closest(".stage").ok().flatten().is_some());
            if on_stage && node_at(event.target()).is_none() {
                state.borrow_mut().drag =
                    Some((f64::from(event.client_x()), f64::from(event.client_y())));
                if let Some(stage) = state.borrow().stage() {
                    let _ = stage.class_list().add_1("panning");
                }
            }
        });
    }
    {
        let state = Rc::clone(&state);
        listen(&window, "mousemove", move |event: MouseEvent| {
            let mut docs = state.borrow_mut();
            if let Some((x, y)) = docs.drag {
                let (nx, ny) = (f64::from(event.client_x()), f64::from(event.client_y()));
                docs.drag = Some((nx, ny));
                docs.pan(nx - x, ny - y);
            }
        });
    }
    {
        let state = Rc::clone(&state);
        listen(&window, "mouseup", move |_: MouseEvent| {
            let mut docs = state.borrow_mut();
            docs.drag = None;
            if let Some(stage) = docs.stage() {
                let _ = stage.class_list().remove_1("panning");
            }
        });
    }
    {
        let state = Rc::clone(&state);
        let closure = Closure::<dyn FnMut(WheelEvent)>::new(move |event: WheelEvent| {
            let mut docs = state.borrow_mut();
            let Some(stage) = docs.stage() else {
                return;
            };
            let inside = event
                .target()
                .and_then(|t| t.dyn_into::<Element>().ok())
                .is_some_and(|el| stage.contains(Some(&el)));
            if !inside {
                return;
            }
            event.prevent_default();
            if event.ctrl_key() || event.meta_key() {
                let rect = stage.get_bounding_client_rect();
                let at = (
                    f64::from(event.client_x()) - rect.left(),
                    f64::from(event.client_y()) - rect.top(),
                );
                docs.zoom((-event.delta_y() * 0.01).exp(), Some(at));
            } else if event.shift_key() {
                docs.pan(-event.delta_y(), 0.0);
            } else {
                docs.pan(-event.delta_x(), -event.delta_y());
            }
        });
        // Not passive: the handler calls preventDefault so the page does not
        // scroll while the reader moves the diagram.
        let options = web_sys::AddEventListenerOptions::new();
        options.set_passive(false);
        let _ = charts.add_event_listener_with_callback_and_add_event_listener_options(
            "wheel",
            closure.as_ref().unchecked_ref(),
            &options,
        );
        closure.forget();
    }

    // The detail panel.
    for (id, delta) in [("d_prev", -1_isize), ("d_next", 1)] {
        let state = Rc::clone(&state);
        listen(
            &crate::element::<Element>(&document, id),
            "click",
            move |_: MouseEvent| {
                state.borrow_mut().step_tour(delta);
            },
        );
    }
    {
        let state = Rc::clone(&state);
        listen(
            &crate::element::<Element>(&document, "d_close"),
            "click",
            move |_: MouseEvent| {
                state.borrow_mut().clear_detail();
            },
        );
    }
    {
        let owned = document.clone();
        listen(
            &crate::element::<Element>(&document, "d_copy"),
            "click",
            move |_: MouseEvent| {
                copy_code(&owned);
            },
        );
    }
    {
        let state = Rc::clone(&state);
        listen(
            &crate::element::<Element>(&document, "d_links"),
            "click",
            move |event: MouseEvent| {
                let target = event
                    .target()
                    .and_then(|t| t.dyn_into::<Element>().ok())
                    .and_then(|el| el.closest("[data-go]").ok().flatten())
                    .and_then(|el| el.get_attribute("data-go"));
                if let Some(id) = target {
                    state.borrow_mut().show_detail(&id);
                }
            },
        );
    }

    // Keys: ← → tour, Enter opens the focused box, Esc closes, F fits,
    // + − zoom, 1–9 switch charts.
    {
        let state = Rc::clone(&state);
        let owned = document.clone();
        listen(&window, "keydown", move |event: KeyboardEvent| {
            if event.ctrl_key() || event.meta_key() || event.alt_key() {
                return;
            }
            let focused = owned.active_element();
            let typing = focused.as_ref().is_some_and(|el| {
                matches!(el.tag_name().as_str(), "INPUT" | "TEXTAREA" | "SELECT")
            });
            if typing {
                return;
            }
            let key = event.key();
            let mut docs = state.borrow_mut();
            match key.as_str() {
                "ArrowRight" | "j" => {
                    event.prevent_default();
                    docs.step_tour(1);
                }
                "ArrowLeft" | "k" => {
                    event.prevent_default();
                    docs.step_tour(-1);
                }
                "Enter" | " " => {
                    let id = focused
                        .and_then(|el| el.closest(".node").ok().flatten())
                        .and_then(|el| el.get_attribute("data-id"));
                    if let Some(id) = id {
                        event.prevent_default();
                        docs.show_detail(&id);
                    }
                }
                "Escape" => docs.clear_detail(),
                "f" | "F" => docs.fit(),
                "+" | "=" => docs.zoom(1.25, None),
                "-" => docs.zoom(0.8, None),
                digit if digit.len() == 1 && digit.chars().all(|c| c.is_ascii_digit()) => {
                    let index = digit.parse::<usize>().unwrap_or(0);
                    let ids: Vec<String> = docs.data["charts"]
                        .as_object()
                        .map(|charts| charts.keys().cloned().collect())
                        .unwrap_or_default();
                    // The page data is an object, which serde_json keeps
                    // sorted; the chart list keeps the document's order.
                    let mut ordered = Vec::new();
                    each(
                        &owned.document_element().expect("root"),
                        ".nav-item",
                        |el| {
                            if let Some(id) = el.get_attribute("data-chart") {
                                if ids.contains(&id) {
                                    ordered.push(id);
                                }
                            }
                        },
                    );
                    if let Some(id) = index.checked_sub(1).and_then(|i| ordered.get(i)) {
                        let id = id.clone();
                        docs.show_chart(&id, None);
                        replace_hash(&format!("#{id}"));
                    }
                }
                _ => {}
            }
        });
    }

    // Back and forward through deep links, and resizing.
    {
        let state = Rc::clone(&state);
        listen(&window, "hashchange", move |_: web_sys::Event| {
            from_hash(&state)
        });
    }
    {
        let state = Rc::clone(&state);
        let closure = Closure::<dyn FnMut()>::new(move || {
            if let Ok(mut docs) = state.try_borrow_mut() {
                docs.resized();
            }
        });
        if let Ok(observer) = web_sys::ResizeObserver::new(closure.as_ref().unchecked_ref()) {
            observer.observe(&charts);
        }
        closure.forget();
    }

    from_hash(&state);
    Ok(())
}
