//! Writes `docs/algorithm-flowcharts.md` from the same chart data as
//! `docs.html`: a mermaid flowchart per algorithm, its notes, and the source
//! of every function a box stands for.

use crate::code;
use crate::spec::{Chart, Lanes, Shape, CHARTS};
use std::fmt::Write as _;

const BLOB: &str = "https://github.com/drdebmath/CCMModel/blob/main";

const HEADER: &str = "# Algorithm flowcharts

One flowchart per algorithm, with the code of every function the chart names.

The charts are the control flow as implemented, not as idealised: where the
implementation departs from a paper, the chart shows what the code does and the
notes say why. Read [behavior-spec.md](behavior-spec.md) for Drop-and-Freeze and
Help-by-Scouts, and [p1tree.md](p1tree.md) for P1Tree, before drawing
conclusions from any of them. The interactive version, [`docs.html`](../docs.html),
explains every box and opens its code.

> Generated by [`scripts/gen-flowcharts.sh`](../scripts/gen-flowcharts.sh) from
> the chart data in [`crates/ccm-docgen/src/spec.rs`](../crates/ccm-docgen/src/spec.rs),
> which also generates `docs.html`. The code blocks are extracted from the
> crates, so editing this file by hand will be overwritten. Re-run the script
> after changing a chart or any function it quotes.

Shapes: rounded = where a run starts or ends, rectangle = a step, diamond = a
question (its arrows are the answers), dashed = a helper the step calls.
";

const FOOTER: &str = "---

## Reading the three together

All three settle one agent per node and all three are depth-first, but they
differ in who does the looking and what the tree is for.

| | Drop and Freeze | Help by Scouts | P1Tree |
| --- | --- | --- | --- |
| Start | one node (several are accepted but can stall) | one node | one node (required) |
| Who probes | unsettled agents, one per port | unsettled agents plus vacated settlers | unsettled agents plus vacated settlers |
| Probe cost | one port per agent per round | parallel across scouts | parallel, and stops at the first find |
| Port labels | overwritten by `canonicalize_ports` | as given | as given, and central to the result |
| Tree | incidental to the walk | carries the retrace | the object being built |
| Stops when | every agent is settled, or the round limit | every agent is settled, or the round limit | every agent is settled, or the round limit |

The port-label row is the one that catches people out. Drop-and-Freeze discards
the port assignment an experiment asked for, so sweeping `--ports` changes
nothing for it; P1Tree's whole behaviour turns on which edges happen to carry
port 1.
";

/// Text for a mermaid label: quotes and angle brackets as entities.
fn label(text: &str) -> String {
    text.replace('"', "#quot;")
        .replace('<', "#lt;")
        .replace('>', "#gt;")
}

fn class(shape: Shape) -> &'static str {
    match shape {
        Shape::Entry => "k_entry",
        Shape::Step => "k_step",
        Shape::Decision => "k_decision",
        Shape::Terminal => "k_end",
        Shape::Aside => "k_aside",
    }
}

fn mermaid(chart: &Chart) -> String {
    let mut out = String::from("```mermaid\nflowchart TD\n");
    out.push_str(
        "    classDef k_entry fill:#e8eaff,stroke:#5b6cf0,color:#111,stroke-width:1.5px\n",
    );
    out.push_str("    classDef k_step fill:#ffffff,stroke:#8b98b3,color:#111\n");
    out.push_str("    classDef k_decision fill:#fff4dc,stroke:#c98a12,color:#111\n");
    out.push_str("    classDef k_end fill:#ddf6ef,stroke:#0f9e82,color:#111,stroke-width:1.5px\n");
    out.push_str(
        "    classDef k_aside fill:#f6f7fa,stroke:#8b98b3,color:#333,stroke-dasharray:4 3\n",
    );

    let node_text = |id: &str| {
        let node = chart.nodes.iter().find(|n| n.id == id).expect("node");
        let text = if node.sub.is_empty() {
            label(node.title)
        } else {
            format!(
                "{}<br/><small>{}</small>",
                label(node.title),
                label(node.sub)
            )
        };
        let (open, close) = match node.shape {
            Shape::Entry | Shape::Terminal => ("([", "])"),
            Shape::Decision => ("{", "}"),
            Shape::Step | Shape::Aside => ("[", "]"),
        };
        format!("{id}{open}\"{text}\"{close}")
    };

    // Lanes become subgraphs; a node belongs to the first lane that covers it.
    let (bands, by_row): (&[(&str, f64, f64)], bool) = match chart.lanes {
        Lanes::Rows(bands) => (bands, true),
        Lanes::Cols(bands) => (bands, false),
    };
    let mut placed = Vec::new();
    for (index, &(name, first, last)) in bands.iter().enumerate() {
        let members: Vec<&str> = chart
            .nodes
            .iter()
            .filter(|n| {
                let at = if by_row { n.row } else { n.col };
                at >= first - 0.5 && at <= last + 0.5 && !placed.contains(&n.id)
            })
            .map(|n| n.id)
            .collect();
        if members.is_empty() {
            continue;
        }
        let _ = writeln!(out, "    subgraph lane{index}[\"{}\"]", label(name));
        for id in &members {
            let _ = writeln!(out, "        {}", node_text(id));
        }
        out.push_str("    end\n");
        placed.extend(members);
    }
    for node in chart.nodes.iter().filter(|n| !placed.contains(&n.id)) {
        let _ = writeln!(out, "    {}", node_text(node.id));
    }
    for edge in chart.edges {
        let arrow = match (edge.aside, edge.label) {
            (false, None) => " --> ".to_owned(),
            (false, Some(text)) => format!(" -- \"{}\" --> ", label(text)),
            (true, None) => " -.-> ".to_owned(),
            (true, Some(text)) => format!(" -. \"{}\" .-> ", label(text)),
        };
        let _ = writeln!(out, "    {}{arrow}{}", edge.from, edge.to);
    }
    for node in chart.nodes {
        let _ = writeln!(out, "    class {} {}", node.id, class(node.shape));
    }
    out.push_str("```\n");
    out
}

/// The whole document. `sources` holds each chart's source file.
pub fn document(sources: &[String]) -> String {
    let mut out = String::from(HEADER);
    out.push_str("\n## Contents\n\n");
    for chart in CHARTS {
        let anchor = chart.title.to_lowercase().replace(' ', "-");
        let _ = writeln!(
            out,
            "- [{}](#{anchor}) — `{}`",
            chart.title, chart.crate_name
        );
    }
    for (chart, source) in CHARTS.iter().zip(sources) {
        let _ = write!(out, "\n---\n\n## {}\n\n", chart.title);
        for paragraph in chart.intro {
            out.push_str(paragraph);
            out.push_str(if paragraph.starts_with("- ") {
                "\n"
            } else {
                "\n\n"
            });
        }
        if chart.intro.last().is_some_and(|p| p.starts_with("- ")) {
            out.push('\n');
        }
        out.push_str(&mermaid(chart));
        out.push_str("\n**Notes**\n\n");
        for note in chart.notes {
            let _ = writeln!(out, "- {note}");
        }
        out.push_str("\n### Code\n\n");
        let mut seen: Vec<&str> = Vec::new();
        for node in chart.nodes {
            let Some(name) = node.func else { continue };
            if seen.contains(&name) {
                continue;
            }
            seen.push(name);
            let found = code::extract(source, name).expect("named function exists");
            let end = found.line + found.text.lines().count() - 1;
            let shown = name.split('@').next().unwrap_or(name);
            let _ = write!(
                out,
                "`{shown}` — [{}:{}]({BLOB}/{}#L{}-L{end})\n\n```rust\n{}\n```\n\n",
                chart.source, found.line, chart.source, found.line, found.text
            );
        }
    }
    out.push_str(FOOTER);
    out
}
